blueprint:
  name: Svetlo se snimacem pohybu a timeoutem
  description: "Ovládání světel podle senzoru obsazenosti a tlačítka s prodlužováním pracovního světla"
  domain: automation
  input:
    occupancy_sensor:
      name: Senzor obsazenosti
      selector:
        entity:
          filter:
            - device_class: occupancy
              domain: binary_sensor
            - device_class: motion
              domain: binary_sensor
    ambient_light:
      name: Senzor okolního osvětlení
      selector:
        entity:
          filter:
            - device_class: illuminance
              domain: sensor
    minimal_ambient:
      name: Minimální osvětlení pro zapnutí nočního světla
      selector:
        number:
          min: 0
          max: 500
          unit_of_measurement: lux

    tlacitko:
      name: Tlačítko
      selector:
        entity:
          filter:
            - domain: binary_sensor
            - domain: input_button

    scene_night_on:
      name: Noční světlo (zapnutí)
      selector:
        target:
          entity:
            domain: scene
    scene_off:
      name: Světlo vypnuto
      selector:
        target:
          entity:
            domain: scene
    scene_work_on:
      name: Pracovní světlo (zapnutí)
      selector:
        target:
          entity:
            domain: scene
    working_light_state:
      name: Stav pracovního světla
      selector:
        entity:
          filter:
            - domain: input_boolean
    timeout_night:
      name: Timeout pro noční světlo (sekundy)
      selector:
        number:
          min: 5
          max: 300
          unit_of_measurement: seconds
    timeout_work:
      name: Timeout pro pracovní světlo (minuty)
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes

mode: restart
max_exceeded: silent

triggers:
  - trigger: state
    entity_id: !input occupancy_sensor
    to: "on"
    id: "occupancy"
  - trigger: state
    entity_id: !input tlacitko
    to: "on"
    id: "tlacitko"

condition: []

actions:
  - choose:
      - conditions:
          - condition: trigger
            id: "occupancy"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input working_light_state
                    state: "on"
                sequence:
                  - wait_for_trigger:
                      - trigger: state
                        entity_id: !input occupancy_sensor
                        to: "off"
                  - alias: "Wait the number of minutes that has been set"
                    delay: !input timeout_work
                  - action: scene.turn_on
                    target: !input scene_off
                  - action: input_boolean.turn_off
                    target:
                      entity_id: !input working_light_state
              - conditions:
                  - condition: numeric_state
                    entity_id: !input ambient_light
                    below: !input minimal_ambient
                sequence:
                  - action: scene.turn_on
                    target: !input scene_night_on
                  - wait_for_trigger:
                      - trigger: state
                        entity_id: !input occupancy_sensor
                        to: "off"
                  - alias: "Wait the number of seconds that has been set"
                    delay: !input timeout_night
                  - action: scene.turn_on
                    target: !input scene_off

      - conditions:
          - condition: trigger
            id: "tlacitko"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input working_light_state
                    state: "on"
                sequence:
                  - choose:
                      - conditions:
                          - condition: state
                            entity_id: !input occupancy_sensor
                            state: "on"
                        sequence:
                          - action: input_boolean.turn_off
                            target:
                              entity_id: !input working_light_state
                          - action: scene.turn_on
                            target: !input scene_night_on
                          - wait_for_trigger:
                              - trigger: state
                                entity_id: !input occupancy_sensor
                                to: "off"
                          - alias: "Wait the number of seconds that has been set"
                            delay: !input timeout_night
                          - action: scene.turn_on
                            target: !input scene_off
                    default:
                      - action: scene.turn_on
                        target: !input scene_off
                      - action: input_boolean.turn_off
                        target:
                          entity_id: !input working_light_state
            default:
              - action: scene.turn_on
                target: !input scene_work_on
              - action: input_boolean.turn_on
                target:
                  entity_id: !input working_light_state
